In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import rna_utils as ru
from sklearn.model_selection import train_test_split

DIST_PATH = "../../data/rnadist_f_all.h5"
dist200_PATH = "../../data/rnadist_filtered200.h5"
dist400_PATH = "../../data/rnadist_filtered400.h5"
META_PATH = "../../data/sources/ArchiveII_with_prob_and_motiv.csv"

In [3]:
dist, meta = ru.load_and_align(corr_path=DIST_PATH, meta_path=META_PATH)
dist200, meta200 = ru.load_and_align(corr_path=dist200_PATH, meta_path=META_PATH)
dist400, meta400 = ru.load_and_align(corr_path=dist400_PATH, meta_path=META_PATH)

In [89]:
fams = meta.fam.unique()
print(fams)
print(meta.shape)
meta.sample(5)

['16s' '23s' '5s' 'RNaseP' 'grp1' 'srp' 'tRNA' 'telomerase' 'tmRNA']
(3864, 8)

,sequence,structure,base_pairs,len,motivos,fam,pseudo_probe,stem
id,,,,,,,,
srp_Leis.braz._SDB-87235,GCCGGAGCGUUGCUCUGUAACCUUCGGGGGCUUCCUAGGUGGAGCG...,((((((((...)))))....(((..)))))).....((((...(((...,"[[1, 31], [2, 30], [3, 29], [4, 16], [5, 15], ...",279,SSSSSSSSHHHSSSSSMMMMSSSHHSSSSSSXXXXXSSSSIIISSS...,srp,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, ..."
srp_Heli.hepa._AE017125,AGCCUUUUCUUAGACCUGUGCAAUGCUAUUUUUAAGCACCGCUUCA...,((((((((((((((.((((((.((((((...(((((....((((.....,"[[1, 107], [2, 106], [3, 105], [4, 104], [5, 1...",108,SSSSSSSSSSSSSSISSSSSSBSSSSSSIIISSSSSIIIISSSSII...,srp,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ..."
tmRNA_Shig.flex._AE005674_1-363,GGGGCUGAUUCUGGAUUCGACGGGAUUUGCGAAACCCAAGGUGCAU...,(((((((.............((((((((.....(.((..(((((((...,"[[1, 359], [2, 358], [3, 357], [4, 356], [5, 3...",363,SSSSSSSMMMMMMMMMMMMMSSSSSSSSIIIIISISSIISSSSSSS...,tmRNA,"[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5s_Vibrio-natriegens-1,UGCCUGGCGACCAUAGUGUUUUGGACCCACCUGACUUCCAUGCCGA...,((((((((((.....((((((((.....((((((...............,"[[1, 120], [2, 119], [3, 118], [4, 117], [5, 1...",121,SSSSSSSSSSMMMMMSSSSSSSSIIIIISSSSSSHHHHHHHHHHHH...,5s,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, ..."
srp_Desu.vulg._AE017311,CCCUCACGCGGCGCUAUCUGACUGAACUCCCCCAGGGCCGGAAGGC...,(((((((((..(((((.((((((.....(((.....(((....)))...,"[[1, 82], [2, 81], [3, 80], [4, 79], [5, 78], ...",82,SSSSSSSSSIISSSSSISSSSSSIIIIISSSIIIIISSSHHHHSSS...,srp,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, ..."

In [91]:
print(meta200.shape)
meta200.head(1)

(1190, 8)

,sequence,structure,base_pairs,len,motivos,fam,pseudo_probe,stem
id,,,,,,,,
16s_A.fulgidus_domain2,UUUAUUGGGCCUAAAGCGUCCGUAGCCGGGCUGGUAAGUCCUCCGG...,.......(((<<...(.((((.(.(((.(((((((.((((((((((...,"[[8, 329], [9, 328], [10, 327], [11, 312], [12...",359,EEEEEEESSSBBBBBSMSSSSISBSSSMSSSSSSSBSSSSSSSSSS...,16s,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ..."

In [86]:
print(meta400.shape)
meta400.head(1)

(2190, 8)

,sequence,structure,base_pairs,len,motivos,fam,pseudo_probe,stem
id,,,,,,,,
16s_A.fulgidus_domain2,UUUAUUGGGCCUAAAGCGUCCGUAGCCGGGCUGGUAAGUCCUCCGG...,.......(((<<...(.((((.(.(((.(((((((.((((((((((...,"[[8, 329], [9, 328], [10, 327], [11, 312], [12...",359,EEEEEEESSSBBBBBSMSSSSISBSSSMSSSSSSSBSSSSSSSSSS...,16s,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ..."

In [95]:
# Save dataset to csv, using in train / valid meta200 or meta400 and in test meta. save as: the id / fam / partition
def filter_ids(full, filtered, fam, split_type):
    save_cols = ["split_type", "fold_name", "fold_number", "partition"]
    cols = ["id", "fold_name", "partition"]
    fam_num = {
        "grp1": 0,
        "tmRNA": 1,
        "tRNA": 2,
        "5s": 3,
        "srp": 4,
        "telomerase": 5,
        "RNaseP": 6,
        "16s": 7,
        "23s": 8,
    }
    # train set
    filtered = filtered.copy().reset_index()
    filtered = filtered[filtered["fam"] != fam]
    train, valid = train_test_split(
        filtered, test_size=0.2, random_state=42, stratify=filtered["fam"]
    )
    train["fold_name"] = fam
    train["partition"] = "train"

    valid["fold_name"] = fam
    valid["partition"] = "valid"
    # test
    full = full.copy().reset_index()
    full = full[full["fam"] == fam]
    full = full[["id", "fam"]]
    full["fold_name"] = fam
    full["partition"] = "test"
    # concat
    df = pd.concat([train[cols], valid[cols], full[cols]], ignore_index=True)
    # df.set_index("id", drop=True)
    df["split_type"] = split_type
    df["fold_number"] = fam_num[fam]
    df.set_index("id", drop=True, inplace=True)
    return df[save_cols]

In [ ]:
SAVE_PATH_ORIG = (
    "/home/gkulemeyer/Documents/Repos/RNA-analysis/DataAnalysis/data/filtered_dataset/"
)

dfs_200 = []
dfs_400 = []
for f in meta.fam.unique():
    dfs_200.append(filter_ids(meta, meta200, f, "ff-rnadist_200"))
    dfs_400.append(filter_ids(meta, meta400, f, "ff-rnadist_400"))
df200 = pd.concat(dfs_200)
df200.to_csv(f"{SAVE_PATH_ORIG}/ArchiveII_rnadist_200.csv", index=True)
df400 = pd.concat(dfs_400)
df400.to_csv(f"{SAVE_PATH_ORIG}/ArchiveII_rnadist_400.csv", index=True)

In [97]:
df2 = pd.read_csv(f"{SAVE_PATH_200}/ArchiveII_rnadist_200.csv", index_col=0)
df2.sample(5)

,split_type,fold_name,fold_number,partition
id,,,,
5s_Finegoldia-magna-2,ff-rnadist_200,srp,4,train
16s_Z.mays_domain4,ff-rnadist_200,grp1,0,train
grp1_b.I1.e.T.thermophila.C1.LSU.1925,ff-rnadist_200,RNaseP,6,train
srp_Gibb.zeae._GSP-229533,ff-rnadist_200,tRNA,2,train
5s_Mycoplasma-flocculare-1,ff-rnadist_200,tmRNA,1,train

In [ ]:

df_ = pd.read_csv(
    "/home/gkulemeyer/Documents/Repos/RNA-analysis/DataAnalysis/data/archiveII_all_splits2.csv"
).query(' split_type == "fam-fold"')
df_.drop(columns=["Unnamed: 0", "Unnamed: 0.1"], inplace=True)
df_.set_index("id", inplace=True)
df_.to_csv(f"{SAVE_PATH_ORIG}/ArchiveII_fam-fold.csv", index=True)

In [102]:
SAVE_PATH_200 = "/home/gkulemeyer/Documents/Repos/RNA-analysis/DataAnalysis/data/filtered_dataset/rnadist/dist_200"
SAVE_PATH_400 = "/home/gkulemeyer/Documents/Repos/RNA-analysis/DataAnalysis/data/filtered_dataset/rnadist/dist_400"

In [105]:
meta[["sequence", "structure", "base_pairs", "len"]]

,sequence,structure,base_pairs,len
id,,,,
16s_A.fulgidus_domain2,UUUAUUGGGCCUAAAGCGUCCGUAGCCGGGCUGGUAAGUCCUCCGG...,.......(((<<...(.((((.(.(((.(((((((.((((((((((...,"[[8, 329], [9, 328], [10, 327], [11, 312], [12...",359
16s_A.fulgidus_domain3,AAGGAAUUGGCGGGGGAGCACUACAACGGGUGGAGCCUGCGGUUUA...,.......(((((.(((((((..((..((((((.((((((((((......,"[[8, 487], [9, 486], [10, 484], [11, 483], [12...",488
16s_A.fulgidus_domain4,ACCGCCCGUCAAGCCACCCGAGUGGGCCAGGGGCGAGGGGGUGGCC...,.(.(..((...((((.(((..(((((((..((((..((((((((((...,"[[2, 97], [4, 94], [7, 90], [8, 89], [12, 84],...",133
16s_A.pyrophilus_domain2,UCACUGGGCGUAAAGCGUCCGCAGCCGGUCGGGUAAGCGGGAUGUC...,................((((...(((.(((((((.(((((((((((...,"[[17, 204], [18, 203], [19, 202], [20, 201], [...",250
16s_A.pyrophilus_domain4,CCGCCCGUCACGCCACGGAAGUCGGUCCGGCCGGAAGUCCCCGAGC...,..(..((...((((.(((..((((((((((((....(.((((..((...,"[[3, 114], [6, 110], [7, 109], [11, 104], [12,...",137
...,...,...,...,...
tmRNA_uncu.bact._TRW-72274-2_1-359,GGGGAUGUUCUGGCUUCGACGCUGGUGAUGAAACUCAAUGAUGCAU...,(((((((............((((((((.(....((((..(((.(((...,"[[1, 355], [2, 354], [3, 353], [4, 352], [5, 3...",359
tmRNA_uncu.bact._TRW-80840-1_1-378,GGGGCUGUCCUGGUUUCGACGUGGGUUCGGGACCGGUGUGGUGCAU...,(((((((............((((((((.....((((.((((..(((...,"[[1, 374], [2, 373], [3, 372], [4, 371], [5, 3...",378
tmRNA_uncu.bact._TRW-80840-2_1-379,GGGGCUGCCCUGGUUUCGACGUGGGUUCGGAAUCGGUGUGGUGCAU...,(((((((............((((((((.....((((.((((..(((...,"[[1, 375], [2, 374], [3, 373], [4, 372], [5, 3...",379
tmRNA_uncu.bact._TRW-80840-3_1-379,GGGGCUGCCCUGGUUUCGACGUGGGUUCGGAAUCGGCGUGGUGCAU...,(((((((............((((((((....(((((.((((..(((...,"[[1, 375], [2, 374], [3, 373], [4, 372], [5, 3...",379
tmRNA_uncu.mari._TRW-363180_1-347,GGGGGCGAAUAGGGUUCGACGUUUCUACUGGACUCCGAAGCGCAUG...,(((((((............((((..(.((...(..(.((...((((...,"[[1, 343], [2, 342], [3, 341], [4, 340], [5, 3...",347

In [119]:
print(df_.head(1))

                            split_type fold_name  fold_number partition
id
5s_Acholeplasma-laidlawii-1   fam-fold      grp1            0     train

In [130]:
SAVE_PATH_ORIG = (
    "/home/gkulemeyer/Documents/Repos/RNA-analysis/DataAnalysis/data/filtered_dataset/"
)

for f in meta.fam.unique():
    for partition in ["train", "valid", "test"]:
        print(f, partition)

        # Filtra los IDs del dataframe de particiones
        ids = df_.query(f'fold_name == "{f}" and partition == "{partition}"').index

        # Verifica si hay IDs para esa combinación
        if len(ids) == 0:
            print("No hay datos para esta combinación.")
            continue

        # Filtra el dataframe meta por esos IDs
        subset = meta.loc[meta.index.intersection(ids)][
            ["sequence", "structure", "base_pairs", "len"]
        ]

        if not subset.empty:
            subset.to_csv(
                f"{SAVE_PATH_ORIG}/fam-fold/{partition}_{f}.csv",
                index=True,
            )

16s train
16s valid
16s test
23s train
23s valid
23s test
5s train
5s valid
5s test
RNaseP train
RNaseP valid
RNaseP test
grp1 train
grp1 valid
grp1 test
srp train
srp valid
srp test
tRNA train
tRNA valid
tRNA test
telomerase train
telomerase valid
telomerase test
tmRNA train
tmRNA valid
tmRNA test

In [132]:
SAVE_PATH_200 = "/home/gkulemeyer/Documents/Repos/RNA-analysis/DataAnalysis/data/filtered_dataset/rnadist/dist_200"

for f in meta.fam.unique():
    for partition in ["train", "valid", "test"]:
        print(f, partition)

        # Filtra los IDs del dataframe de particiones
        ids = df200.query(f'fold_name == "{f}" and partition == "{partition}"').index

        # Verifica si hay IDs para esa combinación
        if len(ids) == 0:
            print("No hay datos para esta combinación.")
            continue

        # Filtra el dataframe meta por esos IDs
        subset = meta.loc[meta.index.intersection(ids)][
            ["sequence", "structure", "base_pairs", "len"]
        ]

        if not subset.empty:
            subset.to_csv(
                f"{SAVE_PATH_200}/{partition}_{f}.csv",
                index=True,
            )

16s train
16s valid
16s test
23s train
23s valid
23s test
5s train
5s valid
5s test
RNaseP train
RNaseP valid
RNaseP test
grp1 train
grp1 valid
grp1 test
srp train
srp valid
srp test
tRNA train
tRNA valid
tRNA test
telomerase train
telomerase valid
telomerase test
tmRNA train
tmRNA valid
tmRNA test

In [134]:
SAVE_PATH_400 = "/home/gkulemeyer/Documents/Repos/RNA-analysis/DataAnalysis/data/filtered_dataset/rnadist/dist_400"

for f in meta.fam.unique():
    for partition in ["train", "valid", "test"]:
        print(f, partition)

        # Filtra los IDs del dataframe de particiones
        ids = df400.query(f'fold_name == "{f}" and partition == "{partition}"').index

        # Verifica si hay IDs para esa combinación
        if len(ids) == 0:
            print("No hay datos para esta combinación.")
            continue

        # Filtra el dataframe meta por esos IDs
        subset = meta.loc[meta.index.intersection(ids)][
            ["sequence", "structure", "base_pairs", "len"]
        ]

        if not subset.empty:
            subset.to_csv(
                f"{SAVE_PATH_400}/{partition}_{f}.csv",
                index=True,
            )

16s train
16s valid
16s test
23s train
23s valid
23s test
5s train
5s valid
5s test
RNaseP train
RNaseP valid
RNaseP test
grp1 train
grp1 valid
grp1 test
srp train
srp valid
srp test
tRNA train
tRNA valid
tRNA test
telomerase train
telomerase valid
telomerase test
tmRNA train
tmRNA valid
tmRNA test