In [1]:
import pandas as pd
import os
from mlflow.tracking import MlflowClient


from utils import get_params_and_metrics
from utils import METRICS, HYPERPARAMETERS, ARCHITECTURE, DATASETS, OTHERS

NOTEBOOK_URI="sqlite:////home/guillermo/Documents/SINC/Research/RNA/AEseq2seq/mlruns.db"
SINC_URI="sqlite:////home/gkulemeyer/Documents/Repos/seq2seq/results/mlflow/mlruns.db"

# Conectar al backend store
client = MlflowClient(tracking_uri=SINC_URI)
experiments = client.search_experiments()
for i,exp in enumerate(experiments):
    print(f"i: {i}, ID: {exp.experiment_id}, Nombre: {exp.name}, Estado: {exp.lifecycle_stage}")

i: 0, ID: 9, Nombre: Mask_with_kernels, Estado: active
i: 1, ID: 8, Nombre: test01, Estado: active
i: 2, ID: 6, Nombre: test2, Estado: active
i: 3, ID: 5, Nombre: test, Estado: active
i: 4, ID: 4, Nombre: Train_test_w_masking, Estado: active
i: 5, ID: 3, Nombre: Test_noise_w_noise, Estado: active
i: 6, ID: 2, Nombre: Train_w_noise_0_1, Estado: active
i: 7, ID: 1, Nombre: Test_script, Estado: active
i: 8, ID: 0, Nombre: Default, Estado: active

In [2]:
pd.options.display.max_columns = 999

In [3]:
n = 0
name = experiments[n].name
id = experiments[n].experiment_id
print(f"Nombre: {name}, ID: {id}, Estado: {experiments[n].lifecycle_stage}")

df_arc = get_params_and_metrics(client, id, ARCHITECTURE  + HYPERPARAMETERS)
for col in ARCHITECTURE:
    print(f"{col}: {df_arc[col].unique()}")
for col in HYPERPARAMETERS:
    print(f"{col}: {df_arc[col].unique()}")

Nombre: Mask_with_kernels, ID: 9, Estado: active
arc_embedding_dim: ['4']
arc_features: ['[4, 4, 4, 8]' '[4, 4, 8]' '[4, 8]' '[4, 4, 4]' '[4, 4]' '[4]']
arc_encoder_blocks: ['3' '2' '1' '0']
arc_num_params: ['1492' '1332' '1172' '1012' '852' '692' '1348' '1188' '1028' '868' '708'
 '548' '1164' '1036' '908' '780' '652' '524' '1068' '940' '812' '684'
 '556' '428' '836' '740' '644' '452' '356' '788' '596' '500' '404' '308'
 '896' '800' '704' '608' '512' '416' '320' '568' '504' '440' '376' '312'
 '248' '520' '456' '392' '328' '264' '200' '240' '208' '176' '144' '112'
 '80']
arc_initial_volume: ['512']
arc_latent_volume: ['128.0' '256.0' '512.0']
arc_num_conv: ['1']
arc_pool_mode: ['max']
arc_up_mode: ['upsample']
arc_addition: ['cat']
arc_skip: ['1' '0']
hyp_device: ['cuda']
hyp_lr: ['0.001']
hyp_scheduler: ['none']
hyp_verbose: ['True']
max_epochs: ['30']
train_swaps: [nan '0.9' '0.7' '0.5' '0.3' '0.2' '0.1' '0.0']
test_swaps: ['0.9' '0.7' '0.5' '0.3' '0.2' '0.1' '0.0' nan]

In [4]:
metr = ['test_loss', 
 'test_F1', 
 'test_Accuracy', 
 'test_Accuracy_seq']

In [5]:
n = 0
name = experiments[n].name
id = experiments[n].experiment_id
print(f"Nombre: {name}, ID: {id}, Estado: {experiments[n].lifecycle_stage}")

# METRICS, HYPERPARAMETERS, ARCHITECTURE, DATASETS, OTHERS
EXTRACT = [ 
    "arc_features",
    "arc_encoder_blocks",
    "arc_num_params",
    "arc_latent_volume",
    "arc_num_conv",
    "arc_skip", 
    "arc_kernel",
    "test_swaps",
]

# df_metrics = get_params_and_metrics(client, id, EXTRACT + METRICS)
df_metrics = get_params_and_metrics(client, id, EXTRACT + METRICS)
print(f"df shape: {df_metrics.shape}")
df_metrics.sample(6)

Nombre: Mask_with_kernels, ID: 9, Estado: active
df shape: (4032, 21)

,run_name,arc_features,arc_encoder_blocks,arc_num_params,arc_latent_volume,arc_num_conv,arc_skip,arc_kernel,test_swaps,train_loss,valid_loss,test_loss,valid_F1,train_F1,test_F1,train_Accuracy,valid_Accuracy,test_Accuracy,train_Accuracy_seq,valid_Accuracy_seq,test_Accuracy_seq
3239,skip0_kernel9_noise_0.1_n4_2_n8_0,"[4, 4, 4]",2,608,128.0,1,0,9,NaN,0.127519,0.117599,NaN,0.508965,0.509730,NaN,0.509730,0.508965,NaN,0.0,0.0,NaN
1296,skip0_kernel13_noise_0.5_n4_1_n8_1-0.9,"[4, 4, 8]",2,1068,256.0,1,0,13,0.9,NaN,NaN,0.160588,NaN,NaN,0.280227,NaN,NaN,0.280227,NaN,NaN,0.0
999,skip1_kernel5_noise_0.7_n4_1_n8_0,"[4, 4]",1,312,256.0,1,1,5,NaN,0.108002,0.003541,NaN,0.999896,0.518931,NaN,0.518931,0.999896,NaN,0.0,0.0,NaN
3565,skip1_kernel11_noise_0.0_n4_1_n8_1-0.1,"[4, 4, 8]",2,1036,256.0,1,1,11,0.1,NaN,NaN,0.018293,NaN,NaN,0.923080,NaN,NaN,0.923080,NaN,NaN,0.0
2378,skip0_kernel7_noise_0.2_n4_2_n8_1-0.5,"[4, 4, 4, 8]",3,868,128.0,1,0,7,0.5,NaN,NaN,0.145806,NaN,NaN,0.355828,NaN,NaN,0.355828,NaN,NaN,0.0
3742,skip0_kernel3_noise_0.0_n4_0_n8_1-0.0,"[4, 8]",1,308,512.0,1,0,3,0.0,NaN,NaN,0.057986,NaN,NaN,0.830143,NaN,NaN,0.830143,NaN,NaN,0.0

In [6]:
df_metrics['name'] = df_metrics['run_name']
df_metrics['name']

0       skip1_kernel13_noise_0.9_n4_2_n8_1-0.9
1       skip1_kernel13_noise_0.9_n4_2_n8_1-0.7
2       skip1_kernel13_noise_0.9_n4_2_n8_1-0.5
3       skip1_kernel13_noise_0.9_n4_2_n8_1-0.3
4       skip1_kernel13_noise_0.9_n4_2_n8_1-0.2
                         ...
4027     skip0_kernel3_noise_0.0_n4_0_n8_0-0.3
4028     skip0_kernel3_noise_0.0_n4_0_n8_0-0.2
4029     skip0_kernel3_noise_0.0_n4_0_n8_0-0.1
4030     skip0_kernel3_noise_0.0_n4_0_n8_0-0.0
4031         skip0_kernel3_noise_0.0_n4_0_n8_0
Name: name, Length: 4032, dtype: object

In [7]:
df_metrics['train_swaps'] = df_metrics['run_name'].str.extract(r'noise_([0-9.]+)')
df_metrics['train_swaps'] = df_metrics['train_swaps'].astype(float)
df_metrics

,run_name,arc_features,arc_encoder_blocks,arc_num_params,arc_latent_volume,arc_num_conv,arc_skip,arc_kernel,test_swaps,train_loss,valid_loss,test_loss,valid_F1,train_F1,test_F1,train_Accuracy,valid_Accuracy,test_Accuracy,train_Accuracy_seq,valid_Accuracy_seq,test_Accuracy_seq,name,train_swaps
0,skip1_kernel13_noise_0.9_n4_2_n8_1-0.9,"[4, 4, 4, 8]",3,1492,128.0,1,1,13,0.9,NaN,NaN,0.134490,NaN,NaN,0.393348,NaN,NaN,0.393348,NaN,NaN,0.0,skip1_kernel13_noise_0.9_n4_2_n8_1-0.9,0.9
1,skip1_kernel13_noise_0.9_n4_2_n8_1-0.7,"[4, 4, 4, 8]",3,1492,128.0,1,1,13,0.7,NaN,NaN,0.108631,NaN,NaN,0.529185,NaN,NaN,0.529185,NaN,NaN,0.0,skip1_kernel13_noise_0.9_n4_2_n8_1-0.7,0.9
2,skip1_kernel13_noise_0.9_n4_2_n8_1-0.5,"[4, 4, 4, 8]",3,1492,128.0,1,1,13,0.5,NaN,NaN,0.082518,NaN,NaN,0.661576,NaN,NaN,0.661576,NaN,NaN,0.0,skip1_kernel13_noise_0.9_n4_2_n8_1-0.5,0.9
3,skip1_kernel13_noise_0.9_n4_2_n8_1-0.3,"[4, 4, 4, 8]",3,1492,128.0,1,1,13,0.3,NaN,NaN,0.056193,NaN,NaN,0.794409,NaN,NaN,0.794409,NaN,NaN,0.0,skip1_kernel13_noise_0.9_n4_2_n8_1-0.3,0.9
4,skip1_kernel13_noise_0.9_n4_2_n8_1-0.2,"[4, 4, 4, 8]",3,1492,128.0,1,1,13,0.2,NaN,NaN,0.043166,NaN,NaN,0.862168,NaN,NaN,0.862168,NaN,NaN,0.0,skip1_kernel13_noise_0.9_n4_2_n8_1-0.2,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4027,skip0_kernel3_noise_0.0_n4_0_n8_0-0.3,[4],0,80,512.0,1,0,3,0.3,NaN,NaN,0.057279,NaN,NaN,0.783240,NaN,NaN,0.783240,NaN,NaN,0.0,skip0_kernel3_noise_0.0_n4_0_n8_0-0.3,0.0
4028,skip0_kernel3_noise_0.0_n4_0_n8_0-0.2,[4],0,80,512.0,1,0,3,0.2,NaN,NaN,0.040739,NaN,NaN,0.854851,NaN,NaN,0.854851,NaN,NaN,0.0,skip0_kernel3_noise_0.0_n4_0_n8_0-0.2,0.0
4029,skip0_kernel3_noise_0.0_n4_0_n8_0-0.1,[4],0,80,512.0,1,0,3,0.1,NaN,NaN,0.024370,NaN,NaN,0.926847,NaN,NaN,0.926847,NaN,NaN,0.0,skip0_kernel3_noise_0.0_n4_0_n8_0-0.1,0.0
4030,skip0_kernel3_noise_0.0_n4_0_n8_0-0.0,[4],0,80,512.0,1,0,3,0.0,NaN,NaN,0.007832,NaN,NaN,1.000000,NaN,NaN,1.000000,NaN,NaN,0.0,skip0_kernel3_noise_0.0_n4_0_n8_0-0.0,0.0
4031,skip0_kernel3_noise_0.0_n4_0_n8_0,[4],0,80,512.0,1,0,3,NaN,0.00804,0.008079,NaN,1.0,1.0,NaN,1.0,1.0,NaN,0.0,0.0,NaN,skip0_kernel3_noise_0.0_n4_0_n8_0,0.0

In [8]:
EXPERIMENT_PATH = os.path.join("Masking", name)
os.makedirs(EXPERIMENT_PATH, exist_ok=True)
df_metrics.to_csv(os.path.join(EXPERIMENT_PATH, "metrics.csv"), index=False)